import React from "react";
import { ShieldCheck } from "lucide-react";
import { businessSupabase } from "./lib/supabase";

const Panel=({children})=><section className="biz-panel">{children}</section>;
const Table=({heads,rows})=><div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>):<tr><td colSpan={heads.length}>Belum ada data.</td></tr>}</tbody></table></div>;
const animalLabel=(data,id)=>data.animals.find(x=>x.id===id)?.animal_code||"—";
const productLabel=(data,id)=>data.products.find(x=>x.id===id)?.name||"—";

export default function AnimalCare({data,organizationId,onRefresh}){
 const [tab,setTab]=React.useState("animals"),[msg,setMsg]=React.useState("");
 const tabs=[["animals","Hewan & Ternak"],["locations","Kandang & Lokasi"],["health","Kesehatan"],["vaccination","Vaksinasi"],["treatment","Perawatan"],["weights","Bobot"],["breeding","Reproduksi"],["feed","Pakan"],["production","Produksi"],["forecast","AI Forecasting"],["reports","Laporan"]];
 const remove=async(table,id)=>{if(!confirm("Hapus record ini?"))return;const r=await businessSupabase.from(table).delete().eq("id",id).eq("organization_id",organizationId);setMsg(r.error?.message||"Record dihapus.");if(!r.error)onRefresh?.()};
 return <><div className="biz-hero"><div><span>JOLIE ANIMAL & VETERINARY OS</span><h1>Animal Recording & Care</h1><p>Identitas, kesehatan, vaksin, perawatan, pakan, reproduksi, produksi dan AI forecasting dalam satu rekam jejak.</p></div><ShieldCheck size={46}/></div>
 <div className="quick-grid">{tabs.map(([id,label])=><button className={"quick"+(tab===id?" active":"")} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>{msg&&<p className="app-note">{msg}</p>}
 {tab==="animals"&&<AnimalMaster data={data} organizationId={organizationId} onRefresh={onRefresh} setMsg={setMsg} remove={remove}/>} {tab==="locations"&&<LocationCrud data={data} organizationId={organizationId} onRefresh={onRefresh}/>} 
 {tab==="health"&&<RecordCrud title="Rekam Kesehatan" table="animal_health_records" rows={data.animalHealth} data={data} organizationId={organizationId} onRefresh={onRefresh} remove={remove} fields={[["animal_id","Hewan","animal"],["recorded_at","Tanggal & waktu","datetime-local"],["record_type","Jenis rekam","select",["observation","diagnosis","treatment","checkup","emergency","death","other"]],["symptoms","Gejala","text"],["diagnosis","Diagnosis","text"],["treatment","Tindakan","text"],["medicine_product_id","Produk/obat","product"],["veterinarian_name","Dokter/petugas","text"],["follow_up_date","Kontrol berikutnya","date"],["status","Status","select",["open","monitoring","resolved"]],["notes","Catatan","text"]]} defaults={{record_type:"observation",status:"open"}}/>}
 {tab==="vaccination"&&<RecordCrud title="Register Vaksinasi" table="animal_vaccinations" rows={data.animalVaccinations} data={data} organizationId={organizationId} onRefresh={onRefresh} remove={remove} fields={[["animal_id","ID hewan","animal"],["vaccination_date","Tanggal vaksin","date"],["disease","Penyakit/target","text"],["vaccine_name","Nama vaksin","text"],["vaccine_batch","Batch vaksin","text"],["dose","Dosis","text"],["route","Rute","text"],["vaccinator_name","Nama vaksinator","text"],["vaccinator_phone","HP vaksinator","text"],["owner_name","Nama pemilik","text"],["owner_phone","HP pemilik","text"],["animal_location_text","Lokasi hewan","text"],["next_due_date","Jadwal berikutnya","date"],["reaction_notes","Reaksi pascavaksin","text"],["source_type","Sumber","select",["government_program","private","self_reported"]],["report_status","Status pelaporan","select",["not_reported","reported","verified"]],["notes","Catatan","text"]]} defaults={{source_type:"private",report_status:"not_reported"}}/>}
 {tab==="treatment"&&<RecordCrud title="Perawatan / Pengobatan" table="animal_treatments" rows={data.animalTreatments} data={data} organizationId={organizationId} onRefresh={onRefresh} remove={remove} fields={[["animal_id","Hewan","animal"],["treatment_date","Tanggal","date"],["complaint","Keluhan","text"],["diagnosis","Diagnosis","text"],["medicine_product_id","Produk/obat JOLIE","product"],["dose","Dosis","text"],["duration","Durasi","text"],["veterinarian_name","Dokter/petugas","text"],["withdrawal_period_days","Withdrawal (hari)","number"],["outcome","Hasil","text"],["notes","Catatan","text"]]}/>}
 {tab==="weights"&&<RecordCrud title="Monitoring Bobot & Kondisi" table="animal_weights" rows={data.animalWeights} data={data} organizationId={organizationId} onRefresh={onRefresh} remove={remove} fields={[["animal_id","Hewan","animal"],["measured_at","Tanggal & waktu","datetime-local"],["weight_kg","Bobot (kg)","number"],["body_condition_score","Body Condition Score","number"],["measurement_method","Metode ukur","text"],["notes","Catatan","text"]]}/>}
 {tab==="breeding"&&<RecordCrud title="Reproduksi & Perkawinan" table="animal_breeding_records" rows={data.animalBreeding} data={data} organizationId={organizationId} onRefresh={onRefresh} remove={remove} fields={[["female_animal_id","Betina","animal"],["male_animal_id","Pejantan","animal"],["breeding_date","Tanggal kawin/IB","date"],["method","Metode","text"],["pregnancy_check_date","Pemeriksaan bunting","date"],["pregnancy_result","Hasil","select",["positive","negative","unknown"]],["expected_birth_date","Perkiraan lahir","date"],["actual_birth_date","Kelahiran aktual","date"],["offspring_count","Jumlah anak","number"],["outcome","Hasil","text"],["veterinarian_name","Dokter/petugas","text"],["notes","Catatan","text"]]}/>}
 {tab==="feed"&&<RecordCrud title="Pencatatan Pakan" table="animal_feed_records" rows={data.animalFeed} data={data} organizationId={organizationId} onRefresh={onRefresh} remove={remove} fields={[["animal_id","Hewan","animal"],["location_id","Kandang/lokasi","location"],["feed_product_id","Produk pakan JOLIE","product"],["feeding_date","Tanggal & waktu","datetime-local"],["quantity","Jumlah","number"],["unit","Satuan","text"],["feed_cost","Biaya pakan","number"],["notes","Catatan","text"]]}/>}
 {tab==="production"&&<RecordCrud title="Produksi Ternak" table="animal_production_records" rows={data.animalProduction} data={data} organizationId={organizationId} onRefresh={onRefresh} remove={remove} fields={[["animal_id","Hewan","animal"],["location_id","Lokasi","location"],["production_date","Tanggal","date"],["production_type","Jenis produksi","select",["milk","egg","meat_weight","offspring","wool","other"]],["quantity","Jumlah","number"],["unit","Satuan","text"],["quality_grade","Mutu/grade","text"],["revenue","Pendapatan","number"],["notes","Catatan","text"]]}/>}
 {tab==="forecast"&&<Forecast data={data} organizationId={organizationId} onRefresh={onRefresh}/>}
 {tab==="reports"&&<Reports data={data}/>}
 </>;
}


function LocationCrud({data,organizationId,onRefresh}){
 const empty={id:null,name:"",location_type:"farm",address:"",village:"",district:"",regency:"",province:"",latitude:"",longitude:"",capacity:"",is_active:true};
 const [form,setForm]=React.useState(empty),[mode,setMode]=React.useState("view"),[search,setSearch]=React.useState(""),[busy,setBusy]=React.useState(false);
 const save=async()=>{if(!form.name.trim())return alert("Nama lokasi wajib diisi.");setBusy(true);const payload={organization_id:organizationId,...form};delete payload.id;["latitude","longitude","capacity"].forEach(k=>{if(payload[k]==="")payload[k]=null;else if(payload[k]!=null)payload[k]=Number(payload[k])});const r=form.id?await businessSupabase.from("animal_locations").update(payload).eq("id",form.id).eq("organization_id",organizationId):await businessSupabase.from("animal_locations").insert(payload);setBusy(false);if(r.error){alert(r.error.message);return}setForm(empty);setMode("view");onRefresh?.()};
 const shown=data.animalLocations.filter(x=>!search||[x.name,x.village,x.district,x.regency,x.province].some(v=>String(v||"").toLowerCase().includes(search.toLowerCase())));
 return <Panel><div className="biz-panel-head"><div><h2>Master Kandang & Lokasi</h2><p>Lokasi terstruktur untuk kandang, farm, coop, stable, rumah, klinik dan lokasi lainnya.</p></div><button className="app-primary" onClick={()=>{setMode("insert");setForm(empty)}}>＋ Insert Lokasi</button></div>
 {mode!=="view"&&<div className="operation-form"><div className="form-grid">
 {["name","address","village","district","regency","province"].map(k=><label key={k}>{({name:"Nama lokasi *",address:"Alamat",village:"Desa/Kelurahan",district:"Kecamatan",regency:"Kabupaten/Kota",province:"Provinsi"})[k]}<input className="app-input" value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
 <label>Jenis lokasi<select className="app-input" value={form.location_type} onChange={e=>setForm({...form,location_type:e.target.value})}>{["farm","barn","coop","cage","stable","clinic","home","other"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Kapasitas<input className="app-input" type="number" value={form.capacity||""} onChange={e=>setForm({...form,capacity:e.target.value})}/></label>
 <label>Latitude<input className="app-input" type="number" step="any" value={form.latitude||""} onChange={e=>setForm({...form,latitude:e.target.value})}/></label>
 <label>Longitude<input className="app-input" type="number" step="any" value={form.longitude||""} onChange={e=>setForm({...form,longitude:e.target.value})}/></label>
 <label className="form-check"><input type="checkbox" checked={!!form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Aktif</label>
 </div><div className="form-actions"><button className="app-primary" disabled={busy} onClick={save}>{busy?"Menyimpan…":form.id?"Update":"Insert"}</button><button className="app-btn" onClick={()=>{setMode("view");setForm(empty)}}>Batal</button></div></div>}
 <div className="hardware-row"><input className="app-input" placeholder="Cari lokasi, desa, kecamatan…" value={search} onChange={e=>setSearch(e.target.value)}/><span className="app-note">{shown.length} lokasi</span></div>
 <Table heads={["Nama","Jenis","Wilayah","Kapasitas","Status","Aksi"]} rows={shown.map(x=>[x.name,x.location_type,[x.village,x.district,x.regency,x.province].filter(Boolean).join(" / ")||"—",x.capacity??"—",x.is_active?"Aktif":"Nonaktif",<span className="form-actions"><button className="app-btn" onClick={()=>{setForm({...empty,...x});setMode("update")}}>Detail / Update</button><button className="app-warn" onClick={()=>removeLocation(x.id,organizationId,onRefresh)}>Delete</button></span>])}/></Panel>
}
async function removeLocation(id,organizationId,onRefresh){if(!confirm("Hapus lokasi ini? Hewan yang masih mereferensikan lokasi akan kehilangan referensi lokasinya."))return;const r=await businessSupabase.from("animal_locations").delete().eq("id",id).eq("organization_id",organizationId);if(r.error)alert(r.error.message);else onRefresh?.()}

function AnimalMaster({data,organizationId,onRefresh,setMsg,remove}){
 const empty={id:null,animal_code:"",name:"",animal_class:"livestock",species_id:"",breed_id:"",production_purpose:"",sex:"unknown",birth_date:"",estimated_age_months:"",color:"",identification_type:"ear_tag",identification_number:"",customer_id:"",location_id:"",origin:"",acquisition_date:"",acquisition_method:"",status:"active",dam_id:"",sire_id:"",notes:""};
 const [form,setForm]=React.useState(empty),[mode,setMode]=React.useState("view"),[search,setSearch]=React.useState(""),[busy,setBusy]=React.useState(false);
 const breeds=data.breeds.filter(x=>!form.species_id||x.species_id===form.species_id);
 const save=async()=>{if(!form.animal_code||!form.species_id)return setMsg("ID hewan dan jenis wajib diisi.");setBusy(true);const payload={organization_id:organizationId,...form};delete payload.id;["breed_id","customer_id","location_id","dam_id","sire_id","birth_date","acquisition_date"].forEach(k=>{if(payload[k]==="")payload[k]=null});if(payload.estimated_age_months==="")payload.estimated_age_months=null;const r=form.id?await businessSupabase.from("animals").update(payload).eq("id",form.id).eq("organization_id",organizationId):await businessSupabase.from("animals").insert(payload);setBusy(false);setMsg(r.error?.message||(form.id?"Hewan diperbarui.":"Hewan berhasil diinsert."));if(!r.error){setMode("view");setForm(empty);onRefresh?.()}};
 const filtered=data.animals.filter(x=>!search||[x.animal_code,x.name,x.identification_number].some(v=>String(v||"").toLowerCase().includes(search.toLowerCase())));
 const select=(k,label,opts)=><label>{label}<select className="app-input" value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}><option value="">— pilih —</option>{opts.map(o=><option key={o[0]??o} value={o[0]??o}>{o[1]??o}</option>)}</select></label>;
 return <Panel><div className="biz-panel-head"><div><h2>Master Hewan & Ternak</h2><p>Individu, ras, pemilik/member, lokasi, identitas, umur, kelamin, asal dan status.</p></div><button className="app-primary" onClick={()=>{setMode("insert");setForm(empty)}}>＋ Insert Hewan</button></div>
 {mode!=="view"&&<div className="operation-form"><div className="form-grid">
 <label>ID Hewan *<input className="app-input" value={form.animal_code} onChange={e=>setForm({...form,animal_code:e.target.value})}/></label><label>Nama/panggilan<input className="app-input" value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/></label>
 {select("animal_class","Kelas",["livestock","pet"])}{select("species_id","Jenis",data.species.map(x=>[x.id,x.name]))}{select("breed_id","Ras",breeds.map(x=>[x.id,x.name]))}{select("sex","Kelamin",["male","female","unknown"])}
 <label>Tujuan pemeliharaan<input className="app-input" value={form.production_purpose||""} onChange={e=>setForm({...form,production_purpose:e.target.value})}/></label><label>Tanggal lahir<input className="app-input" type="date" value={form.birth_date||""} onChange={e=>setForm({...form,birth_date:e.target.value})}/></label>
 <label>Umur estimasi (bulan)<input className="app-input" type="number" value={form.estimated_age_months||""} onChange={e=>setForm({...form,estimated_age_months:e.target.value})}/></label><label>Warna/ciri<input className="app-input" value={form.color||""} onChange={e=>setForm({...form,color:e.target.value})}/></label>
 <label>Tipe identitas<input className="app-input" value={form.identification_type||""} onChange={e=>setForm({...form,identification_type:e.target.value})}/></label><label>Nomor tag/identitas<input className="app-input" value={form.identification_number||""} onChange={e=>setForm({...form,identification_number:e.target.value})}/></label>
 {select("customer_id","Pemilik/member",data.customers.map(x=>[x.id,x.name]))}{select("location_id","Kandang/lokasi",data.animalLocations.map(x=>[x.id,x.name]))}
 <label>Asal<input className="app-input" value={form.origin||""} onChange={e=>setForm({...form,origin:e.target.value})}/></label><label>Tanggal diperoleh<input className="app-input" type="date" value={form.acquisition_date||""} onChange={e=>setForm({...form,acquisition_date:e.target.value})}/></label>
 <label>Cara diperoleh<input className="app-input" value={form.acquisition_method||""} onChange={e=>setForm({...form,acquisition_method:e.target.value})}/></label>{select("status","Status",["active","sold","dead","transferred","lost","inactive"])}
 {select("dam_id","Induk betina",data.animals.filter(x=>x.sex!=="male").map(x=>[x.id,x.animal_code]))}{select("sire_id","Induk jantan",data.animals.filter(x=>x.sex!=="female").map(x=>[x.id,x.animal_code]))}
 <label>Catatan<textarea className="app-input" rows="3" value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
 </div><div className="form-actions"><button className="app-primary" disabled={busy} onClick={save}>{busy?"Menyimpan…":form.id?"Update":"Insert"}</button><button className="app-btn" onClick={()=>{setMode("view");setForm(empty)}}>Batal</button></div></div>}
 <div className="hardware-row"><input className="app-input" placeholder="Cari ID, nama atau tag…" value={search} onChange={e=>setSearch(e.target.value)}/><span className="app-note">{filtered.length} hewan</span></div>
 <Table heads={["ID","Jenis","Ras","Kelamin","Pemilik","Lokasi","Status","Aksi"]} rows={filtered.map(x=>[x.animal_code,data.species.find(s=>s.id===x.species_id)?.name||"—",data.breeds.find(b=>b.id===x.breed_id)?.name||"—",x.sex,data.customers.find(c=>c.id===x.customer_id)?.name||"—",data.animalLocations.find(l=>l.id===x.location_id)?.name||"—",x.status,<span className="form-actions"><button className="app-btn" onClick={()=>{setForm({...empty,...x});setMode("update")}}>Detail / Update</button><button className="app-warn" onClick={()=>remove("animals",x.id)}>Delete</button></span>])}/></Panel>
}

function RecordCrud({title,table,rows,data,organizationId,onRefresh,remove,fields,defaults={}}){
 const [mode,setMode]=React.useState("view"),[editing,setEditing]=React.useState(null),[form,setForm]=React.useState(defaults),[search,setSearch]=React.useState(""),[busy,setBusy]=React.useState(false);
 const reset=()=>{setMode("view");setEditing(null);setForm({...defaults})};
 const options=(type)=>type==="animal"?data.animals.map(x=>[x.id,x.animal_code]):type==="product"?data.products.map(x=>[x.id,x.name]):type==="location"?data.animalLocations.map(x=>[x.id,x.name]):[];
 const save=async()=>{setBusy(true);const payload={organization_id:organizationId};fields.forEach(([k,,type])=>{let v=form[k];if(type==="number")v=v===""?0:Number(v);payload[k]=v===""?null:v});const r=editing?await businessSupabase.from(table).update(payload).eq("id",editing).eq("organization_id",organizationId):await businessSupabase.from(table).insert(payload);setBusy(false);if(r.error){alert(r.error.message);return}reset();onRefresh?.()};
 const edit=row=>{setEditing(row.id);setMode("update");setForm({...defaults,...row})};
 const shown=rows.filter(r=>!search||fields.some(([k])=>String(r[k]??"").toLowerCase().includes(search.toLowerCase())));
 const label=(row,k,type)=>type==="animal"?animalLabel(data,row[k]):type==="product"?productLabel(data,row[k]):type==="location"?data.animalLocations.find(x=>x.id===row[k])?.name||"—":row[k]??"—";
 return <Panel><div className="biz-panel-head"><div><h2>{title}</h2><small>Insert · Detail/Update · Delete · Search tersambung ke database.</small></div><div className="form-actions"><button className="app-btn" onClick={reset}>Daftar</button><button className="app-primary" onClick={()=>{setMode("insert");setEditing(null);setForm({...defaults})}}>＋ Insert</button></div></div>
 {mode!=="view"&&<div className="operation-form"><div className="form-grid">{fields.map(([k,label,type,opts])=>type==="animal"||type==="product"||type==="location"||type==="select"?<label key={k}>{label}<select className="app-input" value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}><option value="">— pilih —</option>{(type==="select"?opts:options(type)).map(o=><option key={o[0]??o} value={o[0]??o}>{o[1]??o}</option>)}</select></label>:<label key={k}>{label}<input className="app-input" type={type} value={form[k]??""} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="form-actions"><button className="app-primary" disabled={busy} onClick={save}>{busy?"Menyimpan…":mode==="update"?"Update":"Insert"}</button><button className="app-btn" onClick={reset}>Batal</button></div></div>}
 <div className="hardware-row"><input className="app-input" placeholder={"Cari "+title+"…"} value={search} onChange={e=>setSearch(e.target.value)}/><span className="app-note">{shown.length} record</span></div>
 <Table heads={["Record","Status","Aksi"]} rows={shown.map(row=>[<div>{fields.slice(0,5).map(([k,label,type])=><div key={k}><b>{label}:</b> {label==="Hewan"||k.includes("animal_id")||k.includes("female_animal_id")||k.includes("male_animal_id")?animalLabel(data,row[k]):label.includes("Produk")||k.includes("product_id")?productLabel(data,row[k]):row[k]??"—"}</div>)}</div>,row.status||row.report_status||"—",<span className="form-actions"><button className="app-btn" onClick={()=>edit(row)}>Detail / Update</button><button className="app-warn" onClick={()=>remove(table,row.id)}>Delete</button></span>])}/></Panel>
}

function Forecast({data,organizationId,onRefresh}){
 const [busy,setBusy]=React.useState(false),[msg,setMsg]=React.useState("");
 const generate=async()=>{setBusy(true);const rows=data.animals.map(a=>{const ws=data.animalWeights.filter(w=>w.animal_id===a.id).sort((x,y)=>new Date(y.measured_at)-new Date(x.measured_at));const health=data.animalHealth.filter(h=>h.animal_id===a.id&&h.status!=="resolved").length;const last=ws[0],prev=ws[1];let risk=a.status==="active"?.15:.8;if(health)risk=Math.min(.95,risk+.2*health);let predicted=last?.weight_kg??null;if(last&&prev)predicted=Math.max(0,Number(last.weight_kg)+(Number(last.weight_kg)-Number(prev.weight_kg))*30);return{organization_id:organizationId,animal_id:a.id,forecast_type:"health_risk",forecast_date:new Date().toISOString().slice(0,10),horizon_days:30,risk_score:risk,predicted_value:predicted,unit:predicted==null?null:"kg",confidence:last&&prev?.weight_kg?.length?.62:.35,model_version:"JOLIE-Forecast-v1-rule-based",evidence:{open_health:health,weights:ws.slice(0,3)},recommendation:risk>.6?"Perlu pemeriksaan petugas/dokter hewan.":"Pantau rutin dan tambah data recording.",status:"generated"}});
 if(rows.length){const r=await businessSupabase.from("animal_ai_forecasts").insert(rows);setMsg(r.error?.message||("Forecast dibuat untuk "+rows.length+" hewan."));if(!r.error)onRefresh?.()}else setMsg("Belum ada hewan.");setBusy(false)};
 return <Panel><div className="biz-panel-head"><div><h2>AI Forecasting</h2><p>Forecast awal berbasis data recording. Bukan diagnosis dan tidak menggantikan dokter hewan.</p></div><button className="app-primary" disabled={busy} onClick={generate}>{busy?"Menganalisis…":"Generate Forecast"}</button></div>{msg&&<p className="app-note">{msg}</p>}<Table heads={["Hewan","Risiko","Prediksi","Confidence","Model","Rekomendasi","Status"]} rows={data.animalForecasts.map(x=>[animalLabel(data,x.animal_id),x.risk_score==null?"—":(Number(x.risk_score)*100).toFixed(0)+"%",x.predicted_value==null?"—":x.predicted_value+" "+(x.unit||""),(Number(x.confidence||0)*100).toFixed(0)+"%",x.model_version,x.recommendation,x.status])}/></Panel>
}

function Reports({data}){
 const due=data.animalVaccinations.filter(v=>v.next_due_date&&new Date(v.next_due_date)<new Date(Date.now()+30*86400000));
 const open=data.animalHealth.filter(x=>x.status!=="resolved");
 const production=data.animalProduction.reduce((s,x)=>s+Number(x.quantity||0),0);
 return <><Panel><div className="biz-panel-head"><div><h2>Laporan Peternakan & Hewan</h2><p>Populasi, kesehatan, vaksin, produksi dan sinyal AI dari database JOLIE.</p></div><button className="app-btn" onClick={()=>window.print()}>Cetak</button></div><div className="biz-kpis"><KPI label="Hewan aktif" v={data.animals.filter(x=>x.status==="active").length}/><KPI label="Ternak" v={data.animals.filter(x=>x.animal_class==="livestock").length}/><KPI label="Peliharaan" v={data.animals.filter(x=>x.animal_class==="pet").length}/><KPI label="Kasus terbuka" v={open.length}/><KPI label="Vaksin ≤30 hari" v={due.length}/><KPI label="Produksi tercatat" v={production}/></div></Panel><Panel><h3>Populasi per jenis</h3><Table heads={["Jenis","Aktif"]} rows={data.species.map(s=>[s.name,data.animals.filter(a=>a.species_id===s.id&&a.status==="active").length])}/></Panel><Panel><h3>Vaksin jatuh tempo</h3><Table heads={["Hewan","Target","Tanggal","Status"]} rows={due.map(v=>[animalLabel(data,v.animal_id),v.disease,v.next_due_date,v.report_status])}/></Panel><Panel><h3>Kesehatan terbuka</h3><Table heads={["Hewan","Jenis","Diagnosis","Petugas","Status"]} rows={open.map(x=>[animalLabel(data,x.animal_id),x.record_type,x.diagnosis||"—",x.veterinarian_name||"—",x.status])}/></Panel></>
}
const KPI=({label,v})=><div className="biz-kpi"><small>{label}</small><strong>{v}</strong></div>;
