import React from "react";
import { ArrowLeft, Boxes, BrainCircuit, CircleDollarSign, ClipboardList, Database, LayoutDashboard, RefreshCw, ShoppingBag, ShoppingCart, Store, Users, Plus, Minus, ShieldCheck } from "lucide-react";
import { businessSupabase } from "./lib/supabase";

const APPS = [
 {id:"erp",label:"JOLIE ERP",desc:"Command center lintas fungsi",icon:Database},
 {id:"pos",label:"JOLIE POS",desc:"Kasir dan transaksi",icon:ShoppingCart},
 {id:"warehouse",label:"JOLIE Warehouse",desc:"Stok, gudang dan mutasi",icon:Boxes},
 {id:"sales",label:"JOLIE Sales",desc:"Order dan fulfillment",icon:ShoppingBag},
 {id:"procurement",label:"JOLIE Procurement",desc:"Supplier dan pengadaan",icon:ClipboardList},
 {id:"finance",label:"JOLIE Finance",desc:"Payment dan ledger",icon:CircleDollarSign},
 {id:"crm",label:"JOLIE CRM",desc:"Pelanggan dan follow-up",icon:Users},
 {id:"ai",label:"JOLIE AI",desc:"Intelligence lintas aplikasi",icon:BrainCircuit},
 {id:"commerce",label:"JOLIE Commerce",desc:"Website dan e-commerce",icon:Store}
];
const ROLE_APPS={owner:APPS.map(x=>x.id),admin:APPS.map(x=>x.id),manager:APPS.map(x=>x.id),sales:["erp","pos","sales","ai","commerce"],inventory:["erp","warehouse","ai"],procurement:["erp","procurement","warehouse","ai"],finance:["erp","finance","sales","ai"],crm:["erp","crm","ai","commerce"]};
function rupiah(v){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));}
function date(v){return v?new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";}

export default function BusinessApps({appId="launcher",onBack}){
 const [access,setAccess]=React.useState(null),[loading,setLoading]=React.useState(true),[error,setError]=React.useState(""),[refreshing,setRefreshing]=React.useState(false);
 const [data,setData]=React.useState({products:[],inventory:[],warehouses:[],orders:[],customers:[],suppliers:[],purchaseOrders:[],payments:[],ledger:[],activities:[]});
 const load=React.useCallback(async()=>{
  if(!businessSupabase){setLoading(false);return;} setRefreshing(true);
  const {data:a,error:e}=await businessSupabase.rpc("jolie_my_access"); const acc=a?.[0];
  if(e||!acc){setAccess(null);setError("Akun tidak memiliki role Business OS.");setLoading(false);setRefreshing(false);return;}
  setAccess(acc); const org=acc.organization_id;
  const jobs={
   products:businessSupabase.from("products").select("id,name,sku,unit,price,stock_qty,min_stock_qty,is_active").eq("organization_id",org).order("name"),
   inventory:businessSupabase.from("inventory").select("id,warehouse_id,product_id,quantity,reserved_quantity,reorder_point,updated_at").eq("organization_id",org).order("updated_at",{ascending:false}).limit(300),
   warehouses:businessSupabase.from("warehouses").select("id,name,code,is_active").eq("organization_id",org).order("name"),
   orders:businessSupabase.from("sales_orders").select("id,order_number,status,payment_status,total,created_at,customer_id").eq("organization_id",org).order("created_at",{ascending:false}).limit(100),
   customers:businessSupabase.from("customers").select("id,name,phone,email,created_at").eq("organization_id",org).order("created_at",{ascending:false}).limit(200),
   suppliers:businessSupabase.from("suppliers").select("id,name,phone,email,is_active").eq("organization_id",org).order("name"),
   purchaseOrders:businessSupabase.from("purchase_orders").select("id,po_number,status,subtotal,created_at,supplier_id,warehouse_id").eq("organization_id",org).order("created_at",{ascending:false}).limit(100),
   payments:businessSupabase.from("payment_transactions").select("id,order_id,method,status,amount,created_at").eq("organization_id",org).order("created_at",{ascending:false}).limit(100),
   ledger:businessSupabase.from("finance_ledger").select("id,entry_type,direction,amount,account_code,reference_type,reference_id,description,created_at").eq("organization_id",org).order("created_at",{ascending:false}).limit(200),
   activities:businessSupabase.from("crm_activities").select("id,customer_id,activity_type,subject,body,due_at,completed_at,created_at").eq("organization_id",org).order("created_at",{ascending:false}).limit(100)
  };
  const entries=await Promise.all(Object.entries(jobs).map(async([k,p])=>[k,await p])); const next={products:[],inventory:[],warehouses:[],orders:[],customers:[],suppliers:[],purchaseOrders:[],payments:[],ledger:[],activities:[]}; const errs=[];
  entries.forEach(([k,r])=>{next[k]=r.data||[];if(r.error)errs.push(k+": "+r.error.message);}); setData(next);setError(errs.join(" · "));setLoading(false);setRefreshing(false);
 },[]);
 React.useEffect(()=>{load();},[load]);
 if(loading)return <Shell title="JOLIE Business Apps" onBack={onBack}><Panel>Menyiapkan koneksi antar-aplikasi…</Panel></Shell>;
 if(!access)return <Shell title="Akses belum tersedia" onBack={onBack}><Panel><ShieldCheck size={30}/><h2>Role staff belum tersedia</h2><p>{error}</p><button className="app-btn" onClick={onBack}>Kembali ke login Business OS</button></Panel></Shell>;
 const allowed=(ROLE_APPS[access.role]||[]).includes(appId);
 if(!allowed)return <Shell title="Aplikasi dibatasi" access={access} onBack={onBack}><Panel><ShieldCheck size={30}/><h2>Aplikasi tidak tersedia untuk role {access.role}</h2><p>Launcher dan RLS sama-sama membatasi akses.</p></Panel></Shell>;
 return <Shell title={appId==="launcher"?"JOLIE Application Launcher":(APPS.find(x=>x.id===appId)?.label||"JOLIE Business App")} access={access} onBack={onBack} onRefresh={load} refreshing={refreshing}>{error&&<div className="app-error">{error}</div>}{appId==="launcher"&&<Launcher access={access}/>} {appId==="erp"&&<ERP data={data}/>} {appId==="pos"&&<POS products={data.products} customers={data.customers} onRefresh={load}/>} {appId==="warehouse"&&<Warehouse products={data.products} inventory={data.inventory} warehouses={data.warehouses} onRefresh={load}/>} {appId==="sales"&&<Sales orders={data.orders} customers={data.customers}/>} {appId==="procurement"&&<Procurement suppliers={data.suppliers} purchaseOrders={data.purchaseOrders} warehouses={data.warehouses}/>} {appId==="finance"&&<Finance payments={data.payments} ledger={data.ledger}/>} {appId==="crm"&&<CRM customers={data.customers} activities={data.activities} onRefresh={load}/>} {appId==="ai"&&<AI data={data}/>} {appId==="commerce"&&<Commerce/>}</Shell>;
}
function Shell({children,title,access,onBack,onRefresh,refreshing}){return <div className="biz-app-shell"><header className="biz-app-top"><div className="biz-app-brand"><div className="biz-app-mark">J</div><div><b>{title}</b><small>{access?.organization_name||"JOLIE"}{access?.role?" · "+access.role:""}</small></div></div><div className="biz-app-actions"><button onClick={onBack}><ArrowLeft size={15}/> Launcher/Login</button>{onRefresh&&<button className="app-primary" onClick={onRefresh} disabled={refreshing}><RefreshCw size={15}/> {refreshing?"Sync…":"Sync"}</button>}</div></header><main className="biz-app-main">{children}</main></div>}
function Panel({children}){return <section className="biz-panel">{children}</section>}
function Launcher({access}){const ids=ROLE_APPS[access.role]||[];return <><div className="biz-hero"><div><span>JOLIE PLATFORM</span><h1>Satu fondasi. Banyak aplikasi kerja.</h1><p>Setiap aplikasi memiliki UX dan workflow sendiri, tetapi identity, product master, customer master, inventory, payment dan audit tetap terintegrasi.</p></div><Database size={46}/></div><div className="biz-grid">{APPS.filter(a=>ids.includes(a.id)).map(a=>{const I=a.icon;return <button className="biz-card" key={a.id} onClick={()=>window.location.href="./"+a.id+"/"}><I size={26}/><b>{a.label}</b><span>{a.desc}</span><em>Buka aplikasi →</em></button>})}</div><Panel><b>Kontrak data bersama</b><div className="architecture"><span>Identity + RBAC</span><span>Product Master</span><span>Customer Master</span><span>Inventory Ledger</span><span>Payment Ledger</span><span>Audit Events</span></div></Panel></>}
function ERP({data}){const sales=data.orders.reduce((s,o)=>s+Number(o.total||0),0),paid=data.payments.filter(x=>x.status==="paid").reduce((s,x)=>s+Number(x.amount||0),0),low=data.products.filter(p=>Number(p.stock_qty)<=Number(p.min_stock_qty)).length;return <><div className="biz-kpis"><K label="Produk" v={data.products.length}/><K label="Order" v={data.orders.length}/><K label="Nilai order" v={rupiah(sales)}/><K label="Paid" v={rupiah(paid)}/><K label="Risiko stok" v={low}/></div><Panel><h2>Command Center</h2><p>ERP mengagregasi sinyal lintas aplikasi tanpa mengambil alih transaksi aplikasi spesifik.</p><div className="quick-grid">{["pos","warehouse","sales","procurement","finance","crm","ai"].map(id=><button className="quick" key={id} onClick={()=>window.location.href="./"+id+"/"}>{APPS.find(x=>x.id===id)?.label}</button>)}</div></Panel></>}
function K({label,v}){return <div className="biz-kpi"><small>{label}</small><strong>{v}</strong></div>}
function HardwarePanel(){const [msg,setMsg]=React.useState("");const [barcode,setBarcode]=React.useState("");const [device,setDevice]=React.useState("");const [busy,setBusy]=React.useState(false);async function queue(type){setBusy(true);const u=(await businessSupabase.auth.getUser()).data.user;const {error}=await businessSupabase.from("print_jobs").insert({organization_id:(await businessSupabase.rpc("jolie_my_access")).data?.[0]?.organization_id,job_type:type,payload:{source:"pos",barcode},status:"queued",requested_by:u?.id,device_id:device||null});setMsg(error?.message||type+" masuk antrean.");setBusy(false)}return <Panel><h3>Hardware & Print</h3><div className="hardware-row"><input className="app-input" placeholder="Barcode scanner input" value={barcode} onChange={e=>setBarcode(e.target.value)}/><input className="app-input" placeholder="Device ID (opsional)" value={device} onChange={e=>setDevice(e.target.value)}/><button className="app-primary" disabled={busy} onClick={()=>queue("receipt")}>Cetak Struk</button><button className="app-btn" disabled={busy} onClick={()=>queue("label")}>Cetak Label</button></div>{msg&&<p className="app-note">{msg}</p>}<small>Perangkat fisik bekerja melalui adapter/agent; browser tidak mengakses EDC, USB printer, atau cash drawer secara langsung tanpa jalur yang sesuai.</small></Panel>}
function POS({products,customers,onRefresh}){const [cart,setCart]=React.useState([]),[q,setQ]=React.useState(""),[method,setMethod]=React.useState("cash"),[customer,setCustomer]=React.useState(""),[msg,setMsg]=React.useState(""),[busy,setBusy]=React.useState(false);const list=products.filter(p=>p.is_active&&p.price!=null&&(!q||p.name.toLowerCase().includes(q.toLowerCase())||String(p.sku||"").toLowerCase().includes(q.toLowerCase()))).slice(0,30);const total=cart.reduce((s,x)=>s+x.price*x.qty,0);const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{id:p.id,name:p.name,price:Number(p.price),qty:1}]});async function pay(){if(!cart.length||busy)return;setBusy(true);setMsg("");const {data,error}=await businessSupabase.rpc("jolie_pos_create_sale",{p_items:cart.map(x=>({product_id:x.id,quantity:x.qty})),p_payment_method:method,p_amount:total,p_customer_id:customer||null,p_idempotency_key:crypto.randomUUID()});if(error)setMsg(error.message);else{setMsg("Transaksi "+(data?.order_number||"berhasil")+" tercatat.");setCart([]);onRefresh?.();}setBusy(false)}return <><HardwarePanel/><div className="biz-split"><Panel><input className="app-input" placeholder="Cari produk / SKU" value={q} onChange={e=>setQ(e.target.value)}/><div className="product-grid">{list.map(p=><button className="product" key={p.id} onClick={()=>add(p)}><ShoppingCart size={16}/><b>{p.name}</b><span>{rupiah(p.price)} · stok {p.stock_qty}</span></button>)}</div></Panel><Panel><h2>Keranjang Kasir</h2>{customers.length>0&&<select className="app-input" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Walk-in</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}{cart.map(x=><div className="cart-row" key={x.id}><span>{x.name}<small>{x.qty} × {rupiah(x.price)}</small></span><button onClick={()=>setCart(c=>c.filter(i=>i.id!==x.id))}>×</button></div>)}<h2 className="total">{rupiah(total)}</h2><div className="pay-grid">{["cash","qris","bank_transfer","edc"].map(m=><button className={method===m?"selected":""} onClick={()=>setMethod(m)} key={m}>{m.replace("_"," ")}</button>)}</div><button className="app-primary wide" disabled={!cart.length||busy} onClick={pay}>{busy?"Memproses…":"Selesaikan Transaksi"}</button>{msg&&<p className="app-note">{msg}</p>}</Panel></div></>
function Warehouse({products,inventory,warehouses,onRefresh}){const [product,setProduct]=React.useState(""),[warehouse,setWarehouse]=React.useState(""),[qty,setQty]=React.useState(""),[msg,setMsg]=React.useState("");async function adjust(delta){setMsg("");if(!product||!warehouse||!qty)return setMsg("Pilih produk, gudang dan jumlah.");const {data,error}=await businessSupabase.rpc("jolie_inventory_adjust",{p_product_id:product,p_warehouse_id:warehouse,p_quantity_delta:delta*Number(qty),p_movement_type:delta>0?"receipt":"adjustment",p_note:"Warehouse app"});setMsg(error?.message||("Stok baru: "+data?.quantity));if(!error){setQty("");onRefresh?.()}}return <><Panel><h2>Mutasi stok</h2><div className="form-grid"><select className="app-input" value={product} onChange={e=>setProduct(e.target.value)}><option value="">Produk</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="app-input" value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">Gudang</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name} ({w.code})</option>)}</select><input className="app-input" type="number" min="0.01" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Jumlah"/><button className="app-primary" onClick={()=>adjust(1)}><Plus size={15}/> Terima</button><button className="app-warn" onClick={()=>adjust(-1)}><Minus size={15}/> Koreksi keluar</button></div>{msg&&<p className="app-note">{msg}</p>}</Panel><Panel><h2>Snapshot persediaan</h2><Table heads={["Produk","Gudang","Qty","Reserved","Reorder"]} rows={inventory.map(i=>[products.find(p=>p.id===i.product_id)?.name||i.product_id,warehouses.find(w=>w.id===i.warehouse_id)?.name||"—",i.quantity,i.reserved_quantity,i.reorder_point])}/></Panel></>}
function Sales({orders,customers}){return <Panel><h2>Sales & Fulfillment</h2><Table heads={["Order","Pelanggan","Status","Payment","Total","Tanggal"]} rows={orders.map(o=>[o.order_number,customers.find(c=>c.id===o.customer_id)?.name||"Walk-in",o.status,o.payment_status,rupiah(o.total),date(o.created_at)])}/></Panel>}
function Procurement({suppliers,purchaseOrders,warehouses}){return <><div className="biz-kpis"><K label="Supplier aktif" v={suppliers.filter(s=>s.is_active).length}/><K label="Purchase order" v={purchaseOrders.length}/><K label="Warehouse" v={warehouses.length}/></div><Panel><h2>Procurement</h2><Table heads={["PO","Supplier","Status","Subtotal","Tanggal"]} rows={purchaseOrders.map(p=>[p.po_number,suppliers.find(s=>s.id===p.supplier_id)?.name||"—",p.status,rupiah(p.subtotal),date(p.created_at)])}/></Panel></>}
function Finance({payments,ledger}){const paid=payments.filter(p=>p.status==="paid").reduce((s,p)=>s+Number(p.amount||0),0);return <><div className="biz-kpis"><K label="Payment paid" v={rupiah(paid)}/><K label="Payment records" v={payments.length}/><K label="Ledger entries" v={ledger.length}/></div><Panel><h2>Payment Ledger</h2><Table heads={["Metode","Status","Amount","Tanggal"]} rows={payments.map(p=>[p.method,p.status,rupiah(p.amount),date(p.created_at)])}/></Panel><Panel><h2>Finance Ledger</h2><Table heads={["Type","Direction","Account","Amount","Description"]} rows={ledger.map(x=>[x.entry_type,x.direction,x.account_code,rupiah(x.amount),x.description||"—"])}/></Panel></>}
function CRM({customers,activities,onRefresh}){const [customer,setCustomer]=React.useState(""),[subject,setSubject]=React.useState(""),[body,setBody]=React.useState(""),[msg,setMsg]=React.useState("");async function add(){if(!customer||!subject)return setMsg("Pilih pelanggan dan isi subjek.");const {error}=await businessSupabase.rpc("jolie_crm_add_activity",{p_customer_id:customer,p_activity_type:"note",p_subject:subject,p_body:body||null});setMsg(error?.message||"Aktivitas tersimpan.");if(!error){setSubject("");setBody("");onRefresh?.()}}return <><Panel><h2>Tambah aktivitas pelanggan</h2><div className="form-grid"><select className="app-input" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Pelanggan</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} {c.phone?"· "+c.phone:""}</option>)}</select><input className="app-input" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subjek"/><input className="app-input" value={body} onChange={e=>setBody(e.target.value)} placeholder="Catatan"/><button className="app-primary" onClick={add}>Simpan aktivitas</button></div>{msg&&<p className="app-note">{msg}</p>}</Panel><Panel><h2>Customer timeline</h2><Table heads={["Pelanggan","Aktivitas","Subjek","Tanggal"]} rows={activities.map(a=>[customers.find(c=>c.id===a.customer_id)?.name||"—",a.activity_type,a.subject,date(a.created_at)])}/></Panel></>}
function AI({data}){const low=data.products.filter(p=>Number(p.stock_qty)<=Number(p.min_stock_qty)),pending=data.orders.filter(o=>!["completed","cancelled","delivered"].includes(o.status));return <div className="biz-split"><Panel><BrainCircuit size={30}/><h2>JOLIE AI Intelligence</h2><p>Read-only pada tahap ini. Insight berasal dari data lintas aplikasi yang benar-benar tersedia.</p><div className="insight">Produk aktif: {data.products.filter(p=>p.is_active).length}</div><div className="insight">Risiko stok: {low.length}</div><div className="insight">Order belum selesai: {pending.length}</div><div className="insight">Payment: {data.payments.length} · Ledger: {data.ledger.length}</div><div className="insight">CRM: {data.customers.length} pelanggan · {data.activities.length} aktivitas</div></Panel><Panel><h2>Intelligence roadmap</h2><div className="insight">Demand forecasting → sales + inventory + seasonality.</div><div className="insight">Reorder recommendation → stock + supplier lead time.</div><div className="insight">CRM next action → activity + order history.</div><div className="insight">Finance anomaly → payment + ledger + reconciliation.</div></Panel></div>}
function Commerce(){return <Panel><Store size={30}/><h2>JOLIE Commerce</h2><p>Kanal pelanggan dipisahkan dari aplikasi internal, tetapi checkout dan master data tetap terhubung.</p><button className="app-primary" onClick={()=>window.location.href="../../../TOKO-JOLIE-/"}>Buka storefront JOLIE</button></Panel>}
function Table({heads,rows}){return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Belum ada data.</td></tr>}</tbody></table></div>}
