import React from "react";
import { Globe2, LayoutTemplate, Menu, Pencil, Trash2, Settings2 } from "lucide-react";
import { businessSupabase } from "./lib/supabase";

const TYPES=[["website","Website Bisnis"],["ecommerce","E-Commerce"],["blog","Blog"],["landing","Landing Page"],["catalog","Katalog"]];
const TEMPLATES=[["jolie-modern","JOLIE Modern"],["jolie-commerce","JOLIE Commerce"],["jolie-editorial","JOLIE Editorial"],["jolie-local","JOLIE Local"]];
const EMPTY={name:"",slug:"",site_type:"website",template_key:"jolie-modern",description:"",subdomain:"",status:"draft",seo_title:"",seo_description:""};
const slugify=v=>String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70);

export default function SiteFactory({organizationId,onRefresh}){
 const [sites,setSites]=React.useState([]),[pages,setPages]=React.useState([]),[menus,setMenus]=React.useState([]),[blocks,setBlocks]=React.useState([]);
 const [site,setSite]=React.useState(null),[tab,setTab]=React.useState("sites"),[mode,setMode]=React.useState("view"),[form,setForm]=React.useState(EMPTY),[msg,setMsg]=React.useState("");
 const [page,setPage]=React.useState({title:"",slug:"",page_type:"standard",status:"draft",sort_order:0}),[menu,setMenu]=React.useState({label:"",url:"/",sort_order:0}),[block,setBlock]=React.useState({block_type:"hero",title:"",text:"",sort_order:0});
 async function loadSites(){const r=await businessSupabase.from("jolie_sites").select("*").eq("organization_id",organizationId).order("created_at",{ascending:false});if(!r.error)setSites(r.data||[])}
 async function loadSite(s=site){if(!s)return;const [p,m]=await Promise.all([businessSupabase.from("jolie_site_pages").select("*").eq("site_id",s.id).order("sort_order"),businessSupabase.from("jolie_site_menus").select("*").eq("site_id",s.id).order("sort_order")]);if(!p.error)setPages(p.data||[]);if(!m.error)setMenus(m.data||[]);if(p.data?.[0]){const b=await businessSupabase.from("jolie_site_blocks").select("*").eq("page_id",p.data[0].id).order("sort_order");if(!b.error)setBlocks(b.data||[])}}
 React.useEffect(()=>{loadSites()},[organizationId]); React.useEffect(()=>{if(site)loadSite(site)},[site?.id,tab]);
 const select=s=>{setSite(s);setTab("pages");setMode("view");setMsg("")};
 const saveSite=async()=>{if(!form.name.trim())return setMsg("Nama website wajib diisi.");const p={organization_id:organizationId,name:form.name.trim(),slug:slugify(form.slug||form.name),site_type:form.site_type,template_key:form.template_key,description:form.description||null,subdomain:slugify(form.subdomain||form.slug||form.name),status:form.status,seo_title:form.seo_title||null,seo_description:form.seo_description||null};const r=form.id?await businessSupabase.from("jolie_sites").update(p).eq("id",form.id):await businessSupabase.from("jolie_sites").insert(p);setMsg(r.error?.message||(form.id?"Website diupdate.":"Website dibuat."));if(!r.error){setMode("view");setForm(EMPTY);await loadSites();onRefresh?.()}}
 const removeSite=async s=>{if(!confirm("Hapus website dan seluruh isinya?"))return;const r=await businessSupabase.from("jolie_sites").delete().eq("id",s.id);setMsg(r.error?.message||"Website dihapus.");if(!r.error){if(site?.id===s.id)setSite(null;await loadSites();onRefresh?.()}}
 const togglePublish=async s=>{const status=s.status==="published"?"draft":"published";const r=await businessSupabase.from("jolie_sites").update({status}).eq("id",s.id);setMsg(r.error?.message||(status==="published"?"Website dipublikasikan.":"Website kembali draft."));await loadSites()}
 const savePage=async()=>{if(!site||!page.title.trim())return setMsg("Judul halaman wajib.");const p={site_id:site.id,...page,slug:slugify(page.slug||page.title),sort_order:Number(page.sort_order||0)};const r=page.id?await businessSupabase.from("jolie_site_pages").update(p).eq("id",page.id):await businessSupabase.from("jolie_site_pages").insert(p);setMsg(r.error?.message||(page.id?"Page diupdate.":"Page ditambahkan."));if(!r.error){setPage({title:"",slug:"",page_type:"standard",status:"draft",sort_order:0});await loadSite()}}
 const removePage=async p=>{if(!confirm("Hapus page?"))return;const r=await businessSupabase.from("jolie_site_pages").delete().eq("id",p.id);setMsg(r.error?.message||"Page dihapus.");await loadSite()}
 const saveMenu=async()=>{if(!site||!menu.label.trim())return;const r=await businessSupabase.from("jolie_site_menus").insert({site_id:site.id,...menu,sort_order:Number(menu.sort_order||0)});setMsg(r.error?.message||"Menu ditambahkan.");if(!r.error){setMenu({label:"",url:"/",sort_order:0});await loadSite()}}
 const removeMenu=async m=>{const r=await businessSupabase.from("jolie_site_menus").delete().eq("id",m.id);setMsg(r.error?.message||"Menu dihapus.");await loadSite()}
 const addBlock=async()=>{const p=pages[0];if(!p)return setMsg("Buat page dahulu.");const r=await businessSupabase.from("jolie_site_blocks").insert({page_id:p.id,block_type:block.block_type,title:block.title||null,sort_order:Number(block.sort_order||0),content:{text:block.text}});setMsg(r.error?.message||"Block ditambahkan.");if(!r.error){setBlock({block_type:"hero",title:"",text:"",sort_order:0});await loadSite()}}
 const removeBlock=async b=>{const r=await businessSupabase.from("jolie_site_blocks").delete().eq("id",b.id);setMsg(r.error?.message||"Block dihapus.");await loadSite()}
 return <div>
  <div className="biz-hero"><div><span>JOLIE SITE FACTORY · MEMBER PLATFORM</span><h1>Mesin pembuat Website, E-Commerce & Blog.</h1><p>Member membuat properti digital sendiri di dalam namespace JOLIE. Website, halaman, block, menu, SEO dan status publikasi tersimpan sebagai data operasional.</p></div><Globe2 size={46}/></div>
  <div className="quick-grid">{[["sites","Website"],["pages","Pages"],["blocks","Page Builder"],["menus","Navigation"],["settings","SEO & Settings"]].map(x=><button className={"quick"+(tab===x[0]?" active":"")} key={x[0]} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
  {msg&&<div className="insight">{msg}</div>}
  {tab==="sites"&&<Panel><div className="biz-panel-head"><div><h2>Member Site Registry</h2><p>Kelola properti digital member dengan domain namespace JOLIE.</p></div><button className="app-primary" onClick={()=>{setMode("insert");setForm(EMPTY)}}>＋ Website Baru</button></div>
   {(mode==="insert"||mode==="update")&&<div className="operation-form"><div className="form-grid">
    <label>Nama<input className="app-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:form.id?form.slug:slugify(e.target.value),subdomain:form.id?form.subdomain:slugify(e.target.value)})}/></label>
    <label>Slug<input className="app-input" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label>
    <label>Subdomain JOLIE<input className="app-input" value={form.subdomain} onChange={e=>setForm({...form,subdomain:e.target.value})}/></label>
    <label>Jenis<select className="app-input" value={form.site_type} onChange={e=>setForm({...form,site_type:e.target.value})}>{TYPES.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label>
    <label>Template<select className="app-input" value={form.template_key} onChange={e=>setForm({...form,template_key:e.target.value})}>{TEMPLATES.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label>
    <label>Status<select className="app-input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>draft</option><option>published</option><option>archived</option></select></label>
    <label className="full">Deskripsi<textarea className="app-input" rows="3" value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></label>
    <label className="full">SEO Title<input className="app-input" value={form.seo_title||""} onChange={e=>setForm({...form,seo_title:e.target.value})}/></label>
    <label className="full">SEO Description<textarea className="app-input" rows="2" value={form.seo_description||""} onChange={e=>setForm({...form,seo_description:e.target.value})}/></label>
   </div><div className="form-actions"><button className="app-primary" onClick={saveSite}>{form.id?"Update Website":"Insert Website"}</button><button className="app-btn" onClick={()=>{setMode("view");setForm(EMPTY)}}>Batal</button></div></div>}
   <Table heads={["Website","Tipe","Template","Domain JOLIE","Status","Aksi"]} rows={sites.map(s=>[<><b>{s.name}</b><br/><small>{s.description||"—"}</small></>,s.site_type,s.template_key,<code>{s.subdomain}.jolie</code>,s.status,<span className="form-actions"><button className="app-btn" onClick={()=>select(s)}>Kelola</button><button className="app-btn" onClick={()=>{setForm({...EMPTY,...s});setMode("update")}}><Pencil size={14}/> Update</button><button className="app-primary" onClick={()=>togglePublish(s)}>{s.status==="published"?"Unpublish":"Publish"}</button><button className="app-warn" onClick={()=>removeSite(s)}><Trash2 size={14}/> Delete</button></span>])}/></Panel>}
  {tab==="pages"&&<Panel><div className="biz-panel-head"><div><h2>Page Manager</h2><p>{site?.name||"Pilih website pada tab Website."}</p></div></div>{site&&<><div className="form-grid"><input className="app-input" placeholder="Judul page" value={page.title} onChange={e=>setPage({...page,title:e.target.value,slug:slugify(e.target.value)})}/><select className="app-input" value={page.page_type} onChange={e=>setPage({...page,page_type:e.target.value})}>{["home","standard","product","blog","contact","legal"].map(x=><option key={x}>{x}</option>)}</select><button className="app-primary" onClick={savePage}>{page.id?"Update Page":"＋ Insert Page"}</button></div><Table heads={["Page","Type","Status","Order","Aksi"]} rows={pages.map(p=>[p.title,p.page_type,p.status,p.sort_order,<span className="form-actions"><button className="app-btn" onClick={()=>setPage(p)}>Update</button><button className="app-warn" onClick={()=>removePage(p)}>Delete</button></span>])}/></>}</Panel>}
  {tab==="blocks"&&<Panel><div className="biz-panel-head"><div><h2>Visual Page Builder</h2><p>Engine blok: hero, text, image, products, services, FAQ, CTA, contact, footer.</p></div><LayoutTemplate/></div>{site&&pages[0]&&<><div className="form-grid"><select className="app-input" value={block.block_type} onChange={e=>setBlock({...block,block_type:e.target.value})}>{["hero","text","image","products","services","testimonials","faq","cta","contact","footer"].map(x=><option key={x}>{x}</option>)}</select><input className="app-input" placeholder="Judul block" value={block.title} onChange={e=>setBlock({...block,title:e.target.value})}/><input className="app-input" placeholder="Isi block" value={block.text} onChange={e=>setBlock({...block,text:e.target.value})}/><button className="app-primary" onClick={addBlock}>＋ Insert Block</button></div><Table heads={["Order","Block","Judul","Isi","Aksi"]} rows={blocks.map(b=>[b.sort_order,b.block_type,b.title||"—",b.content?.text||"—",<button className="app-warn" onClick={()=>removeBlock(b)}>Delete</button>])}/></>}</Panel>}
  {tab==="menus"&&<Panel><div className="biz-panel-head"><div><h2>Navigation Builder</h2><p>Menu tidak hard-code; member dapat mengelola struktur navigasi.</p></div><Menu/></div>{site&&<><div className="form-grid"><input className="app-input" placeholder="Label menu" value={menu.label} onChange={e=>setMenu({...menu,label:e.target.value})}/><input className="app-input" placeholder="URL / slug" value={menu.url} onChange={e=>setMenu({...menu,url:e.target.value})}/><input className="app-input" type="number" placeholder="Order" value={menu.sort_order} onChange={e=>setMenu({...menu,sort_order:e.target.value})}/><button className="app-primary" onClick={saveMenu}>＋ Insert Menu</button></div><Table heads={["Menu","URL","Order","Aksi"]} rows={menus.map(m=>[m.label,m.url,m.sort_order,<button className="app-warn" onClick={()=>removeMenu(m)}>Delete</button>])}/></>}</Panel>}
  {tab==="settings"&&<Panel><div className="biz-panel-head"><div><h2>SEO & Settings</h2><p>Identitas dan konfigurasi publikasi website.</p></div><Settings2/></div>{site?<><div className="insight"><b>JOLIE URL namespace:</b> {site.subdomain}.jolie<br/><b>Template:</b> {site.template_key}<br/><b>Status:</b> {site.status}<br/><b>SEO:</b> {site.seo_title||"Belum diisi"}</div><button className="app-primary" onClick={()=>{setForm({...EMPTY,...site});setTab("sites");setMode("update")}}>Update Settings</button></>:<p>Pilih website terlebih dahulu.</p>}</Panel>}
 </div>
}
function Panel({children}){return <section className="biz-panel">{children}</section>}
function Table({heads,rows}){return <div className="biz-table-wrap"><table className="biz-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Belum ada data.</td></tr>}</tbody></table></div>}
