revoke update on public.profiles from authenticated;
grant update (full_name, phone, avatar_url, updated_at) on public.profiles to authenticated;
revoke update on public.customers from authenticated;
grant update (name, phone, email, updated_at) on public.customers to authenticated;
revoke update on public.sales_orders from authenticated;
grant update (order_number, status, payment_status, subtotal, shipping_fee, discount, total, updated_at) on public.sales_orders to authenticated;
revoke update on public.sales_order_items from authenticated;
grant update (product_name, quantity, unit_price, line_total) on public.sales_order_items to authenticated;
revoke update on public.products from authenticated;
grant update (category_id, sku, name, slug, description, image_url, unit, price, compare_at_price, stock_qty, min_stock_qty, is_active, is_featured, updated_at) on public.products to authenticated;
revoke update on public.product_categories from authenticated;
grant update (name, slug, icon, image_url, sort_order, is_active) on public.product_categories to authenticated;
revoke update on public.warehouses from authenticated;
grant update (name, code, address, is_active) on public.warehouses to authenticated;
revoke update on public.inventory from authenticated;
grant update (quantity, reserved_quantity, reorder_point, updated_at) on public.inventory to authenticated;
revoke update on public.inventory_movements from authenticated;
grant update (movement_type, quantity_delta, reference_type, reference_id, note) on public.inventory_movements to authenticated;
revoke update on public.suppliers from authenticated;
grant update (name, phone, email, address, is_active, updated_at) on public.suppliers to authenticated;
revoke update on public.purchase_orders from authenticated;
grant update (status, expected_at, subtotal, notes, updated_at) on public.purchase_orders to authenticated;
revoke update on public.purchase_order_items from authenticated;
grant update (product_name, quantity, unit_cost, line_total) on public.purchase_order_items to authenticated;
